"""workflow/state_registry.py — Lifecycle states for each object type."""
STATE_REGISTRY: dict = {
    "TRANSITION_CANDIDATE": {"states":["DISCOVERED","APPROVED","QUEUED","DELAYED","BLOCKED","EXPIRED","EXECUTED","CANCELLED"]},
    "EXECUTION_TICKET":     {"states":["DRAFT","READY","PARTIALLY_EXECUTED","EXECUTED","FAILED","CANCELLED"]},
    "POLICY_CHANGE_REQUEST":{"states":["DRAFT","SUBMITTED","APPROVED","REJECTED","SUPERSEDED","ARCHIVED"]},
    "POLICY_VERSION":       {"states":["DRAFT","SIMULATED","APPROVED","LIVE","ROLLED_BACK","ARCHIVED"]},
    "TRANSITION_JOURNAL":   {"states":["PENDING_OUTCOME","EXECUTED","EVALUATED","ARCHIVED"]},
}
