"""regime/regime_definitions.py — Canonical regime identifiers."""
REGIME_PREMIUM_SELLING    = "PREMIUM_SELLING"
REGIME_NEUTRAL            = "NEUTRAL_TIME_SPREADS"
REGIME_TRENDING           = "TRENDING"
REGIME_LOW_VOL_EXPANSION  = "LOW_VOL_EXPANSION"
REGIME_HIGH_VOL_DEFENSE   = "HIGH_VOL_DEFENSE"

XSP_CREDIT_REGIMES = {REGIME_PREMIUM_SELLING, REGIME_NEUTRAL}
XSP_DEBIT_REGIMES  = {REGIME_TRENDING, REGIME_LOW_VOL_EXPANSION}
