"""auth/permission_matrix.py — Role-to-permission mapping."""
PERMISSION_MATRIX: dict[str, set[str]] = {
    "ANALYST":         {"VIEW_COCKPIT","RUN_SIMULATION","CREATE_CHANGE_REQUEST","VIEW_AUDIT_LOG","EXPORT_RESEARCH"},
    "APPROVER":        {"VIEW_COCKPIT","RUN_SIMULATION","CREATE_CHANGE_REQUEST","APPROVE_POLICY","VIEW_AUDIT_LOG","EXPORT_RESEARCH"},
    "TRADER_OPERATOR": {"VIEW_COCKPIT","EXECUTE_TICKET","VIEW_AUDIT_LOG"},
    "ADMIN":           {"VIEW_COCKPIT","RUN_SIMULATION","CREATE_CHANGE_REQUEST","APPROVE_POLICY",
                        "ACTIVATE_POLICY","ROLLBACK_POLICY","EXECUTE_TICKET","EDIT_REGISTRY",
                        "VIEW_AUDIT_LOG","EXPORT_RESEARCH"},
}
