"""autopilot/delegation_matrix.py — Allowed automation level by environment and action family."""
DELEGATION_MATRIX: dict = {
    "DEV": {
        "QUEUE_RANKING":         "AUTO",
        "REPORT_GENERATION":     "AUTO",
        "ALERT_GENERATION":      "AUTO",
        "REVIEW_CREATION":       "AUTO",
        "REFINEMENT_SUGGESTION": "AUTO",
        "POLICY_SIMULATION":     "AUTO",
        "POLICY_APPROVAL":       "HUMAN_APPROVAL",
        "POLICY_ACTIVATION":     "HUMAN_APPROVAL",
        "CAPITAL_SIZING":        "AUTO_DRAFT",
        "TICKET_DRAFTING":       "AUTO_DRAFT",
        "LIVE_EXECUTION":        "NEVER_AUTOMATE",
        "PRUNING_RECOMMENDATION":"AUTO",
        "RELEASE_ROLLOUT":       "HUMAN_APPROVAL",
    },
    "SIM": {
        "QUEUE_RANKING":         "AUTO",
        "REPORT_GENERATION":     "AUTO",
        "ALERT_GENERATION":      "AUTO",
        "REVIEW_CREATION":       "AUTO",
        "REFINEMENT_SUGGESTION": "AUTO_DRAFT",
        "POLICY_SIMULATION":     "AUTO",
        "POLICY_APPROVAL":       "HUMAN_APPROVAL",
        "POLICY_ACTIVATION":     "HUMAN_APPROVAL",
        "CAPITAL_SIZING":        "AUTO_DRAFT",
        "TICKET_DRAFTING":       "AUTO_DRAFT",
        "LIVE_EXECUTION":        "NEVER_AUTOMATE",
        "PRUNING_RECOMMENDATION":"AUTO_DRAFT",
        "RELEASE_ROLLOUT":       "HUMAN_APPROVAL",
    },
    "LIVE": {
        "QUEUE_RANKING":         "AUTO",
        "REPORT_GENERATION":     "AUTO",
        "ALERT_GENERATION":      "AUTO",
        "REVIEW_CREATION":       "AUTO",
        "REFINEMENT_SUGGESTION": "AUTO_DRAFT",
        "POLICY_SIMULATION":     "AUTO_DRAFT",
        "POLICY_APPROVAL":       "NEVER_AUTOMATE",
        "POLICY_ACTIVATION":     "NEVER_AUTOMATE",
        "CAPITAL_SIZING":        "AUTO_DRAFT",
        "TICKET_DRAFTING":       "AUTO_DRAFT",
        "LIVE_EXECUTION":        "HUMAN_EXECUTION",
        "PRUNING_RECOMMENDATION":"AUTO_DRAFT",
        "RELEASE_ROLLOUT":       "HUMAN_APPROVAL",
    },
}
