"""arch/component_catalog.py — Central inventory of concrete components by layer."""
COMPONENT_CATALOG: dict = {
    "transition_queue_engine":       {"layer":"DECISION",           "kind":"ENGINE", "description":"Ranks actionable transition candidates."},
    "capital_rotation_engine":       {"layer":"DECISION",           "kind":"ENGINE", "description":"Applies capital posture and sizing logic."},
    "narrative_engine":              {"layer":"INTELLIGENCE",        "kind":"ENGINE", "description":"Explains winner, invalidation, and next-step reasoning."},
    "playbook_rank_engine":          {"layer":"INTELLIGENCE",        "kind":"ENGINE", "description":"Ranks playbooks based on evidence."},
    "knowledge_linker":              {"layer":"INTELLIGENCE",        "kind":"ENGINE", "description":"Attaches institutional memory to live decisions."},
    "diagnostics_report_engine":     {"layer":"INTELLIGENCE",        "kind":"ENGINE", "description":"Aggregates block reasons, gate failures, and drag."},
    "policy_simulator":              {"layer":"GOVERNANCE",          "kind":"ENGINE", "description":"Runs non-live policy scenarios."},
    "workflow_engine":               {"layer":"GOVERNANCE",          "kind":"ENGINE", "description":"Manages allowed object state transitions."},
    "policy_activation_engine":      {"layer":"GOVERNANCE",          "kind":"ENGINE", "description":"Promotes approved policy to live."},
    "environment_guard":             {"layer":"GOVERNANCE",          "kind":"ENGINE", "description":"Blocks environment-illegal actions."},
    "alert_rule_engine":             {"layer":"OPERATIONS",          "kind":"ENGINE", "description":"Turns metric thresholds into alerts."},
    "job_runner":                    {"layer":"OPERATIONS",          "kind":"ENGINE", "description":"Executes scheduled jobs."},
    "rollback_watch_engine":         {"layer":"OPERATIONS",          "kind":"ENGINE", "description":"Flags live policy degradation conditions."},
    "review_trigger_engine":         {"layer":"HUMAN_SUPERVISION",   "kind":"ENGINE", "description":"Creates review tasks from issues and findings."},
    "decision_journal_repository":   {"layer":"HUMAN_SUPERVISION",   "kind":"REPOSITORY", "description":"Stores human decisions and rationale."},
    "override_analysis_engine":      {"layer":"HUMAN_SUPERVISION",   "kind":"ENGINE", "description":"Studies system-vs-human divergence."},
    "handoff_queue_engine":          {"layer":"HUMAN_SUPERVISION",   "kind":"ENGINE", "description":"Routes handoffs to correct role."},
    "path_workspace_builder":        {"layer":"EXECUTION_WORKFLOW",  "kind":"ENGINE", "description":"Builds operator work surface from chosen path."},
    "transition_ticket_builder":     {"layer":"EXECUTION_WORKFLOW",  "kind":"ENGINE", "description":"Builds ticket payload from workspace/path context."},
    "blocker_engine":                {"layer":"EXECUTION_WORKFLOW",  "kind":"ENGINE", "description":"Identifies what is preventing action."},
    "refinement_candidate_engine":   {"layer":"ADAPTATION",          "kind":"ENGINE", "description":"Generates evidence-backed improvement candidates."},
    "mandate_weight_engine":         {"layer":"ADAPTATION",          "kind":"ENGINE", "description":"Applies active mandate overlays to scoring."},
    "stress_simulator":              {"layer":"ADAPTATION",          "kind":"ENGINE", "description":"Tests policy + mandate behavior under stress."},
    "component_attribution_engine":  {"layer":"ADAPTATION",          "kind":"ENGINE", "description":"Measures component ROI after value and friction."},
    "pruning_candidate_engine":      {"layer":"ADAPTATION",          "kind":"ENGINE", "description":"Finds simplification targets from evidence."},
    "path_ranker":                   {"layer":"ADAPTATION",          "kind":"ENGINE", "description":"Ranks forward management paths by mandate and evidence."},
    "system_map_builder":            {"layer":"ARCHITECTURE",        "kind":"ENGINE", "description":"Builds the living system map."},
    "impact_trace_engine":           {"layer":"ARCHITECTURE",        "kind":"ENGINE", "description":"Answers what is downstream of a component change."},
}
