"""playbooks/playbook_registry.py — Named playbook universe."""
PLAYBOOKS: dict = {
    "PB001": {"name":"Deep ITM Calendar → Same-Side Diagonal Harvest","family":"DIAGONAL_HARVEST",
              "expected_actions":["FLIP_TO_CALL_DIAGONAL","FLIP_TO_PUT_DIAGONAL"],
              "allowed_rebuild_classes":["KEEP_LONG","REPLACE_LONG"],"min_research_sample":10,
              "research_enabled":True,"promotion_eligible":True,"default_status":"WATCHLIST",
              "use_case":"Stay same-side; harvest short via repeated roll."},
    "PB002": {"name":"Put Calendar → Call Diagonal Skew Flip","family":"OPPOSITE_SIDE_FLIP",
              "expected_actions":["FLIP_TO_CALL_DIAGONAL"],"allowed_rebuild_classes":["KEEP_LONG","REPLACE_LONG"],
              "min_research_sample":10,"research_enabled":True,"promotion_eligible":True,"default_status":"WATCHLIST",
              "use_case":"Flip to call side when call skew richer and put thesis eases."},
    "PB003": {"name":"Call Calendar → Put Diagonal Skew Flip","family":"OPPOSITE_SIDE_FLIP",
              "expected_actions":["FLIP_TO_PUT_DIAGONAL"],"allowed_rebuild_classes":["KEEP_LONG","REPLACE_LONG"],
              "min_research_sample":10,"research_enabled":True,"promotion_eligible":True,"default_status":"WATCHLIST",
              "use_case":"Flip to put side when put skew richer and call thesis eases."},
    "PB004": {"name":"Basis Recovery → Bull Put Collapse","family":"VERTICAL_CONVERSION",
              "expected_actions":["CONVERT_TO_BULL_PUT_SPREAD"],"allowed_rebuild_classes":["REPLACE_LONG"],
              "min_research_sample":10,"research_enabled":True,"promotion_eligible":True,"default_status":"WATCHLIST",
              "use_case":"Convert profitable put path into defined-risk spread; lock basis."},
    "PB005": {"name":"Basis Recovery → Bear Call Collapse","family":"VERTICAL_CONVERSION",
              "expected_actions":["CONVERT_TO_BEAR_CALL_SPREAD"],"allowed_rebuild_classes":["REPLACE_LONG"],
              "min_research_sample":10,"research_enabled":True,"promotion_eligible":True,"default_status":"WATCHLIST",
              "use_case":"Convert profitable call path into defined-risk spread; lock basis."},
    "PB006": {"name":"Delay — Weak Execution Surface","family":"EXECUTION_DELAY",
              "expected_actions":["HOLD_CURRENT_HARVEST"],"allowed_rebuild_classes":[],
              "min_research_sample":5,"research_enabled":True,"promotion_eligible":False,"default_status":"WATCHLIST",
              "use_case":"Surface not rich enough; hold and wait for better vol conditions."},
    "PB007": {"name":"Delay — Weak Timing Window","family":"EXECUTION_DELAY",
              "expected_actions":["HOLD_CURRENT_HARVEST"],"allowed_rebuild_classes":[],
              "min_research_sample":5,"research_enabled":True,"promotion_eligible":False,"default_status":"WATCHLIST",
              "use_case":"Session window unfavorable; defer to next window."},
    "PB008": {"name":"Blocked — Portfolio Allocator","family":"PORTFOLIO_BLOCK",
              "expected_actions":["HOLD_CURRENT_HARVEST"],"allowed_rebuild_classes":[],
              "min_research_sample":5,"research_enabled":True,"promotion_eligible":False,"default_status":"WATCHLIST",
              "use_case":"Portfolio directional or concentration limits block expansion."},
    "PB009": {"name":"Near-Zero Basis Harvest Maintenance","family":"HARVEST_MAINTENANCE",
              "expected_actions":["ROLL_NOW","HARVEST_NOW"],"allowed_rebuild_classes":["KEEP_LONG"],
              "min_research_sample":5,"research_enabled":True,"promotion_eligible":True,"default_status":"WATCHLIST",
              "use_case":"Campaign basis near zero; maintain short harvest only."},
}
