"""playbooks/sop_templates.py — Standard operating procedures per playbook."""
SOP_TEMPLATES: dict = {
    "PB001": {
        "setup":["Current structure is a calendar/diagonal in same-side configuration.",
                 "Transition stays same-side; skew or time-decay justifies rolling the short."],
        "execution":["Close existing short conservatively near ask.",
                     "If REPLACE_LONG: close old long and open replacement at better efficiency.",
                     "Sell new same-side short only if surface and timing are acceptable."],
        "invalidation":["Surface richness fades before execution.",
                        "Campaign basis benefit becomes too small.",
                        "Timing window deteriorates."],
        "next_step":["Harvest the new short leg weekly.",
                     "Reassess flip if skew edge shifts to opposite side.",
                     "Bank when campaign basis approaches zero."],
    },
    "PB002": {
        "setup":["Current structure is a put calendar with sufficient campaign progress.",
                 "Call skew is richer than put skew.",
                 "Transition to call diagonal pays net credit."],
        "execution":["Close put short conservatively.",
                     "If REPLACE_LONG: close old put long; open call long replacement.",
                     "Sell new call short only if surface and timing remain acceptable."],
        "invalidation":["Call skew richness reverses before fill.",
                        "Campaign improvement becomes marginal.",
                        "Path robustness drops under adverse scenario."],
        "next_step":["Harvest new call short weekly.",
                     "Only flip again if skew edge changes materially.",
                     "Consider basis-lock conversion if campaign nears zero."],
    },
    "PB003": {
        "setup":["Current structure is a call calendar.",
                 "Put skew is richer than call skew.",
                 "Transition to put diagonal pays net credit."],
        "execution":["Close call short conservatively.",
                     "If REPLACE_LONG: close old call long; open put long replacement.",
                     "Sell new put short only if surface and timing acceptable."],
        "invalidation":["Put skew richness reverses.","Path becomes fragile.",
                        "Timing or portfolio gate fails."],
        "next_step":["Harvest put short weekly.","Only flip back if call skew re-opens."],
    },
    "PB004": {
        "setup":["Current put path is profitable or near basis recovery.",
                 "Conversion to bull put spread locks basis and cleans structure."],
        "execution":["Close both legs conservatively.",
                     "Open new bull put spread at selected width.",
                     "Verify credit-to-width ratio is acceptable before filling."],
        "invalidation":["Spread width too tight for credit.",
                        "Fill quality degrades before execution."],
        "next_step":["Manage as defined-risk premium structure.",
                     "Favor banking if basis fully recovered."],
    },
    "PB005": {
        "setup":["Current call path is profitable or near basis recovery.",
                 "Conversion to bear call spread locks basis."],
        "execution":["Close both legs conservatively.",
                     "Open new bear call spread at selected width.",
                     "Verify credit-to-width acceptable."],
        "invalidation":["Spread economics deteriorate.","Surface weak for selling calls."],
        "next_step":["Manage as defined-risk structure.","Bank if basis recovered."],
    },
    "PB006": {
        "setup":["Execution surface is weak.",
                 "Short-leg IV not rich enough relative to neighbors."],
        "execution":["DO NOT EXECUTE YET.",
                     "Re-evaluate surface at next session window.",
                     "Only proceed if surface score improves above threshold."],
        "invalidation":["N/A — this IS the delay playbook."],
        "next_step":["Re-check at next session window.",
                     "If surface remains weak after two windows, consider HOLD_CURRENT_HARVEST."],
    },
    "PB007": {
        "setup":["Session timing window is unfavorable.",
                 "Current window scores below threshold for this transition."],
        "execution":["DO NOT EXECUTE NOW.",
                     "Wait for next preferred window.",
                     "Re-evaluate timing score before proceeding."],
        "invalidation":["N/A — this IS the timing-delay playbook."],
        "next_step":["Re-evaluate at next window.",
                     "If still weak, confirm structural approval remains valid."],
    },
    "PB008": {
        "setup":["Portfolio allocator is blocking expansion.",
                 "Directional, symbol, or capital limits reached."],
        "execution":["DO NOT EXPAND.",
                     "Review portfolio posture before proceeding.",
                     "Consider closing other positions to create room."],
        "invalidation":["N/A — this IS the portfolio-block playbook."],
        "next_step":["Re-run allocator after book changes.",
                     "Only proceed when portfolio fit is restored."],
    },
    "PB009": {
        "setup":["Campaign basis is near zero.",
                 "Position is at or close to fully recovered."],
        "execution":["Maintain current short harvest only.",
                     "No new long replacement needed.",
                     "Roll short conservatively; do not over-optimize."],
        "invalidation":["Assignment risk escalates.",
                        "Basis moves negative significantly after new costs."],
        "next_step":["Roll short for net credit each week.",
                     "Consider closing when structure becomes difficult to manage."],
    },
}
